language: ruby
bundler_args: --without debug release
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-2
  - jruby-19mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
