notifications:
  email:
    on_success: never
    on_failure: change
language: ruby
dist: trusty
bundler_args: --without debug release
before_install:
  - ruby -v | (grep -v "rubinius" && gem install bundler) || echo 0
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - rbx-3.69
  - jruby-9.1.5.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
