notifications:
  email:
    on_success: never
    on_failure: change
language: ruby
dist: trusty
bundler_args: --without debug release
before_install:
  - ruby -v | (grep -v "rubinius" && gem install bundler) || echo 0
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - rbx-3.75
  - jruby-9.1.5.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
