language: ruby
bundler_args: --without debug release
before_install:
  - gem install bundler
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
